### ISSUE TITLE
Integrating Youtube API?

### ISSUE THREAD

**Issue by devsnd** [devsnd/cherrymusic#109]
I've seen this many times: once a song is not found, people revert back to youtube, to play one song, just to return to cherrymusic afterwards.

We could integrate the youtube api, so that those songs could be added to the playlist in between.

The search could provide a "search on youtube"-button which would request the youtube videos with the same search terms.

Please don't get me wrong: CherryMusic should provide the means to not having to rely on services like youtube anymore. Nevertheless, just about any music collection lacks this or that song... And I want to listen to that song _right_ _now_.

Any thoughts on this?

**Comment by muhahacz** [comment]
+1 for youtube integratiion.
Actually,there is no server player, thats fully support youtube.
Well, mopidy with mopidy-youtube plugin exists. But complete solution to manage songs, playlists from youtube does not exist.
