### ISSUE TITLE
Flac support!

### ISSUE THREAD

**Issue by PX7057** [devsnd/cherrymusic#121]
I thought this would be an obvious feature, but I was told: "no playable media files found."
Is this a bug or is it simply missing?

**Comment by caffinatedmonkey** [comment]
I kid you not, the latest chrome beta build seems to be able to play FLAC with the native audio element!
![screenshot 2016-01-01 at 2 13 28 pm](https://cloud.githubusercontent.com/assets/3277097/12071885/d9e9cb42-b091-11e5-9b1a-c29450f8bd39.png)

Try it here!
