### ISSUE TITLE
registration options

### ISSUE THREAD

**Issue by hummervdog** [devsnd/cherrymusic#401]
Hi I love Cherry Music. Love Your Work.
I was wondering if there is any way to create a page that could register users?
Like creating email verification if possible.
Is there any way?

**Comment by systems-rebooter** [comment]
> usernames and passwords have to be made up of the letters a-z or numbers, otherwise they wont be accepted.

I'd like paswords to accept !@#$%^&*() to be stronger. How may this be accomplished? Thanks!

**Comment by 6arms1leg** [comment]
Hello @systems-rebooter,

the last post to this issue was over a year ago. I recommend opening a new issue for your requests (and make a reference to this one). This way, it is a lot easier for us to handle things.
Thanks!

**Comment by systems-rebooter** [comment]
Duped in freshly created #553
