### ISSUE TITLE
Add Ability to Sort Songs in Playlist

### ISSUE THREAD

**Issue by marky1991** [devsnd/cherrymusic#463]
E.g. sort by mod. time, create time, title (alphabetical, the default sort (and only sort currently)), length, artist (I'm not currently aware how easy this would be. Haven't looked at the code enough to see.)

If y'all aren't interested in (or don't currently have the time to) implement this, I probably will at some point in the nearish future. I'm just mentioning it in case you guys are looking for work to do. : )

**Comment by MartijnRas** [comment]
Hello,

Can this be added to the file browser as well?

I'd like the file browser to be sort tracks on track number if available.

Mazzel,

Martijn.

**Comment by tilboerner** [comment]
@MartijnRas, I opened issue #525 for your feature request.
