### ISSUE TITLE
Album Art Alignment

### ISSUE THREAD

**Issue by yukip** [devsnd/cherrymusic#501]
![screen shot 2014-12-27 at 12 16 45 am](https://cloud.githubusercontent.com/assets/768421/5560807/f383962a-8d5e-11e4-84cf-812c6984cf60.png)

Every time you click on "browse files" the alignment changes. Different albums will be aligned wrong.

**Comment by yukip** [comment]
This is the css I added to the top of /cherrymusic-devel/res/bootstrap3/gen/cherrymusic.css

h3, .breadcrumb, .list-dir-info-bar{display:none}
.list-dir-item{height:100% !important; vertical-align:middle}
.list-dir{padding-top:5px}

height 100% fixes the problem for me...

**Comment by devsnd** [comment]
cool, you found the problem! do you think you could create a pull request with the changes inside the mediabrowser.less file? if not, I'll put it in there when I find some free time for hacking; I'd do it right now, but I'm on mobile...
