### ISSUE TITLE
Store library in the S3 cloud

### ISSUE THREAD

**Issue by KrzysztofMadejski** [devsnd/cherrymusic#508]
Feature-request:

I imagine a plugin that would allow to store entire music library (and playlists) on external storage. Best would be S3.

A plugin should allow to configuring caching files locally:
- don't cache
- cache directories that files are being played from
- cache playlist played
- precache all content

Also it should allow to set max size of the local cache (doesn't apply to "precache all content"

**Comment by devsnd** [comment]
Hi Krzysiek!

Thanks for your suggestion. Unfortunately I don't have the time to implement cloud storage for CM. You can however try to use a fuse filesystem to mount the basedir on amazon servers. https://code.google.com/p/s3fs/wiki/FuseOverAmazon

I don't know about the performance of this, but maybe it's worth a try. But I cannot guide you any further than this and I don't have the time to implement such a feature, sorry. :crying_cat_face:

**Comment by KrzysztofMadejski** [comment]
Hi @devsnd,

Sorry if my issue sounded like 'please do it'. I've meant "what do you think about it"?

If you think it is a good idea maybe kind of `maybe-in-future` label would be appriopriate if somebody else will have time and desire to implement that. If it doesn't fit in the architecture on the other hand - `won'tfix` is what it should be.

**Comment by 6arms1leg** [comment]
Hello @KrzysztofMadejski,

sorry for (currently) rejecting your feature request. Our time is very limited lately, so we are sticking to the high priority issues at the moment.

> If you think it is a good idea maybe kind of maybe-in-future label would be appriopriate if somebody else will have time and desire to implement that.

I already did that upon issue closure by labeling this issue `feature` and `wontfix`. That's kind of our "internal code words" for closed issues, that may be revised at some point in the future. Check out the closed issues list and apply both of these labels to filter these "maybe-in-future" issues.

Anyway, thanks for your suggestion!
