### ISSUE TITLE
Browse Files: Failed to Load File Browser

### ISSUE THREAD

**Issue by marky1991** [devsnd/cherrymusic#514]
(Note: I realize the name is identical to another recent issue, but this one has a different cause)

I tried updating my version of cherrymusic to head today (and then did a clean checkout in a different directory) and after doing so, the "browse files" button no longer works, giving the forementioned error message and spitting out this traceback in the logs. 

```
[150208-12:33] 10.1.10.1 - - [08/Feb/2015:12:33:56] "POST /api/listdir HTTP/1.1" 500 805 "http://marky1991.com:8800/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36"
[150208-12:34] ERROR   : [08/Feb/2015:12:34:17] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/mark/cherrymusic_test_2_8/cherrymusic/cherrymusicserver/httphandler.py", line 290, in api
    return json.dumps({'data': handler(**handler_args)})
TypeError: api_listdir() takes exactly 2 arguments (1 given)
```

(This error message is from 2.7, but I get an extremely similar traceback in 3.3. (I normally run in 3.3, I just last tested it in 2.7 to see if it was somehow a 3.x-specific issue.))

If any further information is needed, let me know. I'm looking into it on my side as well.

**EDIT (6arms1leg):** Style. Please use Markdown.

**Comment by marky1991** [comment]
PS: if you'd like to see it happen yourself, there's a test account:
Username: "test", password: "test".

 (Probably not the greatest idea to keep that account activated all the time security-wise, now that I think about it...)

**Comment by marky1991** [comment]
Hmm. All I can tell is that by the time it hits `api()` in the server, the data parameter is the string "{}", which from the javascript was supposed to be some directory. The javascript is too complicated for me to get any further. Again, if y'all need any further information, let me know.

**Comment by tilboerner** [comment]
@marky1991, we made a slight change to the api, which breaks old clients when opening the media browser. Both `master` and `devel` work fine for me with a fresh clone; this is likely a cache issue.

If I'm right, you should have no issues
- after clearing your browser cache, or
- with a different browser, or
- when appending ?devel=True to the CherryMusic URL.

Could you let me know if any of these fixes it?

**Comment by marky1991** [comment]
I tried those things but couldn't get the issue to go away.

**Comment by marky1991** [comment]
The stacktrace has changed slightly however:

```python
('listdir',) {'data': '{}'}
[150209-06:52] ERROR   : [09/Feb/2015:06:52:41] HTTP Traceback (most recent call last):
  File "/usr/local/lib/python3.3/dist-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/local/lib/python3.3/dist-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.3/dist-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/mark/cherrymusic_test_2_8/cherrymusic/cherrymusicserver/httphandler.py", line 293, in api
    return json.dumps({'data': handler(**handler_args)})
TypeError: api_listdir() missing 1 required positional argument: 'directory'
```

**Comment by tilboerner** [comment]
Thanks for checking! It looks like CherryMusic is serving an outdated client. Did you install cherrymusic on the server? The static resources (= the client) get copied to and served from a different directory when setup.py is run. 

Any changes made by a subsequent `git pull` will not carry over to this directory. To get these changes to apply, you'll need to install CherryMusic again, using the same procedure as originally. (E.g., run setup.py again.)

To find out which directory is used to serve the client, run cherrymusic with the `--info` switch and look for `static resources dir`. This directory should contain a subdirectory `res` with the same content as the `res` in the cherrymusic repository.

Thanks also for the test account. I had a short look for myself, which was useful, but I agree it's better to disable it.

**Comment by marky1991** [comment]
Heh. Deleting the static media folder and re-running `setup.py` fixed it. (I forgot it even needed to be installed) Sorry for the noise.

**Comment by tilboerner** [comment]
> I forgot it even needed to be installed

Well, technically you don't need to. But CherryMusic tries out the installed directories first
