### ISSUE TITLE
Song Scrollbar on Left

### ISSUE THREAD

**Issue by marky1991** [devsnd/cherrymusic#516]
Is there a reason the scrollbar for the song list in the file browser (not the playlist) is on the left side of its list? In terms of common UIs (that I've used at least. (E.g. every OS I know of)), the scrollbar *never* goes to the left of the content it's controlling (so it feels (for me at least) really wierd for it to be there. Plus, it's inconsistent: the scrollbar for the playlist is on the right of the list.

Obviously this is a design question, so I realize my opinion is just an opinion. But I am wondering why it's there in the first place.

Thanks

**Comment by devsnd** [comment]
Hi Mark,

This was an early design decision, because I found it strange to have a scrollbar in the middle that would scroll the file browser on the left.

In hindsight I agree with you that it's very strange, and I'll change it so that the scrollbars are always on the right side.

**Comment by marky1991** [comment]
Woo, thanks!
