### ISSUE TITLE
Opus support possible?

### ISSUE THREAD

**Issue by lordkitsuna** [devsnd/cherrymusic#517]
I dont know how to set flags like question so forgive me if its wrong. Just wondering if there is or is any plans to support Opus as a codec for transcode. I have tried to look this up but i cant seem to find any information about the subject.

**Comment by devsnd** [comment]
Hi lordkitsuna!

Thanks for the suggestion, opus wasn't supported. But I'm in favor of open formats, so I implemented basic Opus transcoding in the `devel` branch. So check it out and tell me if it works for you. I only did a really quick check and it seemed to work fine.

Have a nice day! :crocodile:

**Comment by 6arms1leg** [comment]
New dependencies?

**Comment by devsnd** [comment]
ah yeah. new optional dependency is `opus-tools`. Thanks for watching out for us :joy_cat:

**Comment by lordkitsuna** [comment]
is devel something i can install from AUR? im fairly new to getting things off git i normally just grab from packman if i need to build from le source i can probably figure it out just wondering. Also would it just use opus when available or is it something i would have to set. Thanks so much for taking the time to add it in!

**Comment by 6arms1leg** [comment]
Hello @lordkitsuna,

yes, we have a [AUR package for the devel branch](https://aur.archlinux.org/packages/cherrymusic-devel-git/).
To install this, extract the tarball and issue (within the directory):
```
$ makepkg
$ sudo pacman -U CHERRYMUSIC_PACKAGE
```
where "CHERRYMUSIC_PACKAGE" is the archive you just created with the `makepkg` command.

To use opus, you have to install the optional dependency `opus-tools`:
```
$ sudo pacman -S --asdeps opus-tools
```
If you have any further questions, please check [our wiki](https://github.com/devsnd/cherrymusic/wiki/Setup-guide), the [cherrymusic wiki page for Arch Linux](https://wiki.archlinux.org/index.php/CherryMusic), the [pacman wiki](https://wiki.archlinux.org/index.php/Pacman) and cherrymusic's man pages first.

**Comment by 6arms1leg** [comment]
If this issue of Opus transcoding is only partially resolved (decoding of Opus files, no encoding to Opus files), why was this issue closed?
:no_good:

**Comment by devsnd** [comment]
That's what I thought the issue was about. Feel free to reopen or open
another issue to include encoding to Opus.

2015-03-02 11:09 GMT+01:00 6arms1leg <notifications@github.com>:

**Comment by lordkitsuna** [comment]
Sorry for not being clear, i was indeed intending to ask about transcode not just decode.

**Comment by devsnd** [comment]
Thanks to @qqueue opus transcoding is now supported! :bee:
