### ISSUE TITLE
Add a public access

### ISSUE THREAD

**Issue by Konubinix** [devsnd/cherrymusic#521]
I want to share some musics with friends in a local network, and I would like only to give the link to the playlist and let them play it, without needing to authenticate.

A workaround could be to add a user called "public" with restricted priviledges and a dumb password, but I wonder if I could have this user authenticated by default, for my friends not to have to perform a dumb authentication.

**Comment by 6arms1leg** [comment]
Good suggestion. Please see #320, thought. :twisted_rightwards_arrows:

**Comment by Konubinix** [comment]
6arms1leg <notifications@github.com> writes:

> Good suggestion. Please see #320, thought.

Well, this indeed is the use case I wanted. Thanks for pointing this out :-).
-- 
Konubinix
GPG Key    : 7439106A
Fingerprint: 5993 BE7A DA65 E2D9 06CE  5C36 75D2 3CED 7439 106A
