### ISSUE TITLE
Getting version through git should be configurable

### ISSUE THREAD

**Issue by MartijnRas** [devsnd/cherrymusic#524]
Hello,

A while back I started noticing defunct git processes on my system.
I finally figured out they coincided with starting cherrymusic.

I've updated the code so one can configure cherrymusic whether or not to get the version through git.

Please have a look at the following commits in my fork:

https://github.com/MartijnRas/cherrymusic/commit/bd6e6520d3ed0f94671583040df18a031c8b0fef
https://github.com/MartijnRas/cherrymusic/commit/6c544304e9690606b10436bd28675af1d40887d4

Mazzel,

Martijn.

**Comment by tilboerner** [comment]
Hi Martijn, thanks for working that one out. Great job on documentation, too! :)

Making `_get_version_from_git` configurable solves the problem, but I'd prefer if there were no defunct git processes at all, even with the option turned on. 

The call to git is really supposed to fail gracefully if anything goes wrong. It could also be deferred until it's needed. If this issue could be solved by ensuring both these things, I'd be glad to avoid the overhead of another configuration option.

Do you have any idea why these processes stay around? They don't seem to when I'm looking. What's your setup like?

**Comment by MartijnRas** [comment]
I guess I sort of shot myself in the foot ...

I'm running on a platform with python 2.7, so I change the first line of [cherrymusic](https://github.com/devsnd/cherrymusic/blob/devel/cherrymusic#L1) from:
  #!/usr/bin/env python3
to:
  #!/usr/bin/env python

Except for these defunct git processes I have not run into any problems.

The problem is in [cherrymusicserver/__init__.py on line 549](https://github.com/devsnd/cherrymusic/blob/devel/cherrymusicserver/__init__.py#L549). Popen does not have context manager support before [Python 3.2](http://bugs.python.org/issue10554).

**Comment by MartijnRas** [comment]
I've refactored the code to make it work below Python 3.2 and added a check to see if there's a '.git' directory.

I've also removed the configuration, as I agree this should be handled gracefully rather than worked around.

**Comment by MartijnRas** [comment]
Closing this now it has been merged.
