### ISSUE TITLE
Guest Public Access

### ISSUE THREAD

**Issue by systems-rebooter** [devsnd/cherrymusic#532]
Hey,

It would be awesome feature to support guest public access. 

Thanks

**Comment by 6arms1leg** [comment]
Thanks for your suggestion!
But please see #320 and #521.

**Comment by systems-rebooter** [comment]
Both issues are closed... Looks like this never been implemented.. I think this is something easy to handle. Or maybe not easy :)

**Comment by systems-rebooter** [comment]
Spamming @6arms1leg with above ^ comment :)

**Comment by 6arms1leg** [comment]
Hm? #320 is open... :open_hands:

**Comment by systems-rebooter** [comment]
My bad.. I believe I mis-looked by creation date `Jun 13, 2013`, which made me think that it definitely closed. Sorry :[
