### ISSUE TITLE
Non ASCII chars in tags not showing correctly (0.35)

### ISSUE THREAD

**Issue by systems-rebooter** [devsnd/cherrymusic#536]
Looks like non ASCII characters in id3 tags not showing correctly, while in names displaying just fine.. See screenshot below:

![screen shot 2015-04-02 at 23 38 58](https://cloud.githubusercontent.com/assets/8888190/6973246/1cbceab2-d992-11e4-8594-0d7856959a5e.png)

Mentioned chars  displaying with mutagen mid3v2 and eyeD3:

```
TPE1=Télépopmusik
artist: Télépopmusik
```
Versions as following: 

```
Python 3.3
CM 0.35 (stable)
```

CM stderr:

```
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/cherrypy/process/plugins.py", line 500, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/lib/python3.3/site-packages/cherrypy/lib/sessions.py", line 577, in clean_up
    contents = self._load(path)
  File "/usr/lib/python3.3/site-packages/cherrypy/lib/sessions.py", line 508, in _load
    return pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdf in position 1: ordinal not in range(128)

Exception in thread Session cleanup:
Traceback (most recent call last):
  File "/usr/lib64/python3.3/threading.py", line 637, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.3/site-packages/cherrypy/process/plugins.py", line 500, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/lib/python3.3/site-packages/cherrypy/lib/sessions.py", line 577, in clean_up
    contents = self._load(path)
  File "/usr/lib/python3.3/site-packages/cherrypy/lib/sessions.py", line 508, in _load
    return pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdf in position 1: ordinal not in range(128)
```

**Comment by tilboerner** [comment]
Looks like tinytag should be using utf-8 to decode the ID3 tags in this case, not latin1. :sob:

Not sure if the breaking session is related. @systems-rebooter, could you zip the contents of your `sessions` directory and send it to `tilman.boerner` at `gmx.net`?

`sessions` is in your cherrymusic data directory: `$HOME/.local/share/cherrymusic` (or locate it by running cherrymusic with the `--info` switch).

**Comment by pando85** [comment]
I have the same problem here:
![cherrymusic_nonasciibug](https://cloud.githubusercontent.com/assets/4646670/7541458/f1828a42-f5b5-11e4-8116-cdd44c317adb.png)

**Comment by tilboerner** [comment]
This is an [issue][] with [tinytag][], which uses the wrong character encoding in these cases. We'll try to get this fixed as soon as possible. If anybody would like to chip in, please feel free to do so over in the tinytag [issue][].

[issue]: https://github.com/devsnd/tinytag/issues/17
[tinytag]: https://github.com/devsnd/tinytag/

**Comment by devsnd** [comment]
Can someone send me an MP3 that exhibits this issue so I can fix tinytag?

**Comment by pando85** [comment]
![cherrymusic - gran dia](https://cloud.githubusercontent.com/assets/4646670/7670939/3ea5192a-fcb9-11e4-9237-ccd4d0ef502e.png)
I upload the mp3 here:
http://s000.tinyupload.com/?file_id=21502534464617341181

Thanks

**Comment by devsnd** [comment]
Hey @pando85, thanks for providing a test file, it became part of the tinytag test suite, so that next time that kind of error will be caught.

I have improved tinytag to completely support UTF-8 and UTF-16-BE encoded ID3v2 tags. This version (which has also improved reading Flac Meta Data) is now in the devel branch of CM, so check it out!

Thanks also @systems-rebooter for reporting all those bugs!

:diamond_shape_with_a_dot_inside: :car: :cop:

**Comment by systems-rebooter** [comment]
@devsnd thanks much, for taking care of it! :car::car::car:
