### ISSUE TITLE
Search by ID3 

### ISSUE THREAD

**Issue by systems-rebooter** [devsnd/cherrymusic#537]
Hey, 

Is it possible to search by ID3 fields? I wasn't able to find something by using id3 fields as search queries. It would be super useful to filter listening 'mood' by music styles in id3. From ambient to dark metal.. 

Not to overkill  performance you can use 'names / tags' search switcher and store id3 info in ~/.local/share/cherrymusic/db/

By the way, what kind of search do you guys using? Is it file-system level search or something else? 

Many thanks!

**Comment by 6arms1leg** [comment]
Hello @systems-rebooter,

please refer to #310 and #5 (wow, look at the issue number! :older_woman:).

The search uses a sqlite database (`~/.local/share/cherrymusic/db/cherry.cache.db`).
