### ISSUE TITLE
high memory usage

### ISSUE THREAD

**Issue by alfwro13** [devsnd/cherrymusic#539]
After recent upgrade I have noticed that Cherrymusic is now eating 350MB out of my 1GB precious memory on my UDOO board.
I'm running CM 0.35.0 on Debian jessie
Any chance that CM could be made bit more memory efficient?
Thx

**Comment by devsnd** [comment]
Hi alfwro13!

Is that virtual memory usage or resource memory usage?

On my home server cherrymusic uses about 31mB resident and about 400mB virtual memory. The virtual memory is however probably just the cached filesystem. If another process needs that memory, it is freed automatically, so there is nothing to worry about.

Here's a [short explaination about memory stats from top/htop](http://mugurel.sumanariu.ro/linux/the-difference-among-virt-res-and-shr-in-top-output/)

If you CM instance really consumes that much memory we'll have dig deeper into why that is.

Thanks for taking the time in reporting! :telephone_receiver: :cactus:

**Comment by alfwro13** [comment]
My bad - actual memory usage is 18MB and 350MB virtual.
Thanks
