### ISSUE TITLE
Cherrymusic server won't start

### ISSUE THREAD

**Issue by lukestorey** [devsnd/cherrymusic#540]
I'm having an odd issue with the server not starting. I can run through the setup and everything, but the server won't ever actually start so that I can get to playing music. I'm confused because it was working earlier...

volumio@volumio:/home/cherrymusic$ sudo python cherrymusic --port 8080
Traceback (most recent call last):
  File "cherrymusic", line 223, in <module>
    cherrymusicserver.start_server(ConfigOptions.configdict)
  File "/home/cherrymusic/cherrymusicserver/__init__.py", line 259, in start_server
    CherryMusic(cfg_override)
  File "/home/cherrymusic/cherrymusicserver/__init__.py", line 309, in __init__
    CherryMusic.create_pid_file()
  File "/home/cherrymusic/cherrymusicserver/__init__.py", line 339, in create_pid_file
    except ProcessLookupError:
NameError: global name 'ProcessLookupError' is not defined

This is the error I'm getting! Any ideas?

**Comment by devsnd** [comment]
Hi lukestorey!

My bad! I just looked it up and [ProcessLookupError is part of python 3.3](https://www.python.org/dev/peps/pep-3151/) and I assume you run something more outdated.

The quickest fix for you would be to switch to a newer python version and then start CM using python 3.3+ instead.

In the mean while I'll fix that as fast as possible.

**Comment by devsnd** [comment]
Hey @lukestorey 

The bug should be fixed now. Just get the latest release (0.35.1) from the [website](http://fomori.org/cherrymusic), [pypi](https://pypi.python.org/pypi/CherryMusic) or [git](https://github.com/devsnd/cherrymusic.git).

Thank you very much for the report!

**Comment by lukestorey** [comment]
Yep! I updated my python and everything started working again. Thank you!


Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Tom Wallroth <notifications@github.com> </div><div>Date:04/10/2015  10:47 AM  (GMT-06:00) </div><div>To: devsnd/cherrymusic <cherrymusic@noreply.github.com> </div><div>Cc: lukestorey <luke.storey@birkelandcurrent.com> </div><div>Subject: Re: [cherrymusic] Cherrymusic server won't start (#540) </div><div>
</div>Hey @lukestorey

The bug should be fixed now. Just get the latest release (0.35.1) from the website, pypi or git.

Thank you very much for the report!

**Comment by 6arms1leg** [comment]
> volumio@volumio:/home/cherrymusic$ sudo python cherrymusic --port 8080

CherryMusic should never run with root permissions!
