### ISSUE TITLE
Default folder images are broken

### ISSUE THREAD

**Issue by tilboerner** [devsnd/cherrymusic#543]
The `src` resolves to `/api/res/img/folder.png`, which has one `/api` too many.

**Comment by devsnd** [comment]
Hm, I cannot reproduce the issue. How do I get there?

**Comment by tilboerner** [comment]
Sorry, not the most detailed bug report up there.

On the current `devel` branch, create an empty dir directly in basedir. Open the media browser in the web client (Firefox 37), the folder has a broken image icon. 

Its `src="http://HOST/api/fetchalbumart/?data=%7B%22directory%22%3A%22THE_DIR_NAME%22%7D"`, the resulting redirect ends up at `http://HOST/api/res/img/folder.png`.

**Comment by devsnd** [comment]
Ah yeah, setting `fetch_album_art` to `False` lets me reproduce it. Seems to be a regression from https://github.com/devsnd/cherrymusic/commit/7f1a527f15b3fb5a4d1d9cc76d16e3c1053f3d17
