### ISSUE TITLE
Windows questions

### ISSUE THREAD

**Issue by blindpet** [devsnd/cherrymusic#548]
I am trying to create a guide for installing on Windows. I have it working mostly but have some questions:
Does sqlite3 have to be part of the path and do I need to pip install some sqlite library?
EDIT working,~~did not have correct folder structure Cover art isn't showing, I have installed Imagemagick-6.9.1-Q8 for 64 bit windows and pip installed wand. Is there anything else I can try?~~

**Comment by tilboerner** [comment]
Hi @blindpet! Python comes with its own sqlite3 module, which needs the sqlite3 *library* to be available. CherryMusic does not need sqlite3.exe (the standalone client) in the PATH. AFAIK it should work out of the box; you should be able to test by running

    python -c "import sqlite3; sqlite3.connect(':memory:')"

in the console. If the library is missing, installing the sqlite3 client might do the trick.

If somebody with more hands-on experience in windows wants to add anything, please go right ahead. :)

**Comment by 6arms1leg** [comment]
> I am trying to create a guide for installing on Windows.

@blindpet, please have a look at the [installation guide for Microsoft Windows in our wiki](https://github.com/devsnd/cherrymusic/wiki/Microsoft-Windows-setup-guide). Instructions are also mentioned in our [setup guide](https://github.com/devsnd/cherrymusic/wiki/Setup-guide#os-specific). Unfortunately, the Windows specific information on both pages is rather basic and incomplete. :broken_heart: If you like, you can also add your findings from your guide there. :construction_worker:

**Comment by blindpet** [comment]
It is a bit basic but I seem to have it all working, I have my own site I create guides for so you are welcome to link to that :) I just published the Raspberry Pi one and it has proven very popular (htpcguides.com).

**Comment by blindpet** [comment]
After I run the initial setup and try to run normally using python cherrymusic I get this error.

`Traceback (most recent call last):
  File "cherrymusic", line 223, in <module>
    cherrymusicserver.start_server(ConfigOptions.configdict)
  File "c:\CherryMusic\cherrymusicserver\__init__.py", line 259, in start_server

    CherryMusic(cfg_override)
  File "c:\CherryMusic\cherrymusicserver\__init__.py", line 309, in __init__
    CherryMusic.create_pid_file()
  File "c:\CherryMusic\cherrymusicserver\__init__.py", line 334, in create_pid_f
ile
    os.getpgid(int(pidfile.read()))
AttributeError: 'module' object has no attribute 'getpgid'`

**Comment by blindpet** [comment]
It seems every time I restart I have to re-setup, I think it has to do with CherryMusic using the appdata folder, can you guys change it so in Windows it uses c:\programdata which I think is 'userless'?

It is making being able to autostart it using vbs or nssm impossible

**Comment by 6arms1leg** [comment]
Hello @blindpet,

thanks a lot for your contribution.
Well, the idea was to make CherryMusic configurable per user, I guess that's why we went with the `appdata` folder. Analogue to GNU/Linux, where the configuration files reside in the home directory of the user.
But if that prevents autostart in Windows, there should something be done about it.

Generally, I recommend opening a new issue for each of your requests (with more expressive titles) -- this helps us to manage/keep track of each individual issue better.

**Comment by blindpet** [comment]
My apologies, will open a new ticket with more details.

**Comment by blindpet** [comment]
@tilboerner that command returned no error so I'm assuming everything is fine with sqlite3 being imported?

**Comment by tilboerner** [comment]
> that command returned no error so I'm assuming everything is fine with sqlite3 being imported?

Yes. Otherwise, CherryMusic also wouldn't be able to index your music, so if you've seen the updater go through your music folder in the server console, or if you can use the search function in the web interface, that's another indication that this part is working as it should.

**Comment by 6arms1leg** [comment]
> will open a new ticket with more details

Reference: #549
