### ISSUE TITLE
Logo Mockup

### ISSUE THREAD

**Issue by blindpet** [devsnd/cherrymusic#550]
I am a total noob at Illustrator but was playing around to try and make the stem turn into the music note. You are welcome to have somebody more experienced to improve it if you are interested in using it.

http://www.mediafire.com/view/6bfgckd0262zf37/cherrymusic2.ai
http://www.mediafire.com/view/6g9lxpd443u44l5/cherrymusic2.png

**Comment by devsnd** [comment]
Hey blindpet,

thanks for you input! I have to admit that I am quite happy with the CM logo as it is right now, but that does not mean that there isn't any room for improvement. If you're into designing UI-stuff, CSS and the like your welcome to improve any graphical part of CM.

have a piece of cake :cake:
