### ISSUE TITLE
Searching not giving back any results

### ISSUE THREAD

**Issue by systems-rebooter** [devsnd/cherrymusic#551]
Hello,

I'm using `CM 0.35` My collection contains few thousands of songs. 
Search not giving back any results on the distinct query (i.e. word / song which **is** in collection)

I'm getting following output from `./cherrymusic`

```
[150422-18:46] WARNING : /ˉˉprocessing whole search request
[150422-18:46] WARNING : |   /ˉˉsearching for a maximum of 400 files
[150422-18:46] WARNING : |   |   /ˉˉfile id fetching
[150422-18:46] WARNING : |   |   \__ 2.72441 ms
[150422-18:46] WARNING : |   |   /ˉˉquerying fullpaths for 0 fileIds
[150422-18:46] WARNING : |   |   \__ 2.98858 ms
[150422-18:46] WARNING : |   \__ 13.7613 ms
[150422-18:46] WARNING : |   /ˉˉsorting DB results using ResultOrder
[150422-18:46] WARNING : |   \__ 2.83527 ms
[150422-18:46] WARNING : |   /ˉˉchecking and classifying results:
[150422-18:46] WARNING : |   \__ 2.51889 ms
[150422-18:46] WARNING : |   /ˉˉrendering search results as json
[150422-18:46] WARNING : |   \__ 2.37036 ms
[150422-18:46] WARNING : \__ 39.6333 ms
``` 

What does `searching for a maximum of 400 files` stands for? Is it searching files threshold I am bumping in? 

My config looks as following:

```
$  egrep -v '^(;|$)'  ~/.config/cherrymusic/cherrymusic.conf
[media]
basedir = /Music/Link
transcode = True
fetch_album_art = False
show_subfolder_count = True
maximum_download_size = 262144000
[search]
maxresults = 100
load_file_db_into_memory = False
[browser]
maxshowfiles = 1000
pure_database_lookup = False
[server]
port = 8080
ipv6_enabled = False
localhost_only = False
rootpath = /
localhost_auto_login = False
permit_remote_admin_login = True
keep_session_in_ram = False
ssl_enabled = False
ssl_port = 8443
ssl_certificate = certs/server.crt
ssl_private_key = certs/server.key
[general]
update_notification = True
```

Thanks!

**Comment by tilboerner** [comment]
It looks like CherryMusic file database doesn't contain what you're looking for. This database currently only works with file and folder names, not ID3 tags; it is also not automatically kept in sync with your music folder (the "basedir" in CherryMusic speak) after the initial scan. It can can get stale if you later:

- add files or directories,
- change your basedir,
- start CherryMusic as another user, or
- delete the CherryMusic's data directory or the base file (`cherry.cache.db`).

To update the database, you have two options:

- in the admin dialog of the web client, click `Update Music Library`; or
- run CherryMusic with the `--update` argument (see `--help`).

Let us know if this helps.

**Comment by systems-rebooter** [comment]
Shame on me... `--update` works perfectly. Thanks much!
I mistakenly thought that restarting CM would be enough to update the library

Do you guys have operators in search? I mean the following: https://support.google.com/websearch/answer/2466433

**Comment by tilboerner** [comment]
Yeah, we made updates on-demand only, because we expect some people to have huuuge collections :elephant:, and collections to not change very often.

> I mistakenly thought that restarting CM would be enough to update the library

If you think that it would make CherryMusic more attractive :cake:, you can always open a [new issue][] to argue for such a scandalous behavior. :)

> Do you guys have operators in search?

There are two so far: You can use `!f` and `!d` (as the first or last term) to limit results to files or directories, respectively.

[new issue]: https://github.com/devsnd/cherrymusic/issues/new

**Comment by systems-rebooter** [comment]
Yeah, updating on-demand sounds more logical and attractive :P 
Impatiently waiting for  `"phrase search"`

**Comment by remsysinc** [comment]
Would like to be able to see ALL songs, not just separated lists based on first num/letter.

**Comment by devsnd** [comment]
@remsysinc 

Increase the `maxshowfiles` in your config file
