### ISSUE TITLE
noob question

### ISSUE THREAD

**Issue by brw31415** [devsnd/cherrymusic#557]
can you tell me the difference between this mp3 streaming server and others out there, such as icecast
and vibe streamer? thanks!

**Comment by devsnd** [comment]
Hi brw π!
I had a quick look on their websites and here are some differences:

vibe streamer:
 - does not support linux (only through wine)
 - does not support audio transcoding
 - has more sophisticated user roles and management

icecast seems to be more like an internet radio, so it allows to create streams for multiple listeners. CherryMusic and Vibe Streamer both only allow individual streaming, like spotify etc does.

Other than that i guess it's up to the users taste to see which one is a better fit. If you're unsure, just try them all out :cake:
