### ISSUE TITLE
jPlayer :: Track Scrolling Not Working Behind Nginx

### ISSUE THREAD

**Issue by systems-rebooter** [devsnd/cherrymusic#562]
Hey,

Looks like track scrolling not working in major desktop browsers behind nginx (no transcoding enabled): 
Also playback disturbing in the middle and start over from the beginning. I'm suspecting jPlayer seeking issue

Chrome FAIL

![screen shot 2015-05-22 at 13 15 02](https://cloud.githubusercontent.com/assets/8888190/7768531/c05c78c2-0084-11e5-8ecb-4058d318d10a.png)

Safari FAIL

![screen shot 2015-05-22 at 13 15 41](https://cloud.githubusercontent.com/assets/8888190/7768534/c72e4248-0084-11e5-9fd0-14af9a3fd9ed.png)

Firefox OK

![screen shot 2015-05-22 at 13 15 31](https://cloud.githubusercontent.com/assets/8888190/7768536/cd46e572-0084-11e5-8881-1dde04eb38da.png)

**Comment by devsnd** [comment]
Hi @systems-rebooter,

Good to see you again! Are you completely sure that this only happens behind nginx? It seems quite weird to me that running CM behind nginx would yield any other outcome in different browsers than accessing it directly.

**Comment by systems-rebooter** [comment]
Hey-hey,

Yeah, it looks like very weird issue, since firefox still seems to be working fine. I reverified it with the simplest logic possible and issue still seems to be there.. 

`location / { proxy_pass http://127.0.0.1:8080/; }`

**Comment by systems-rebooter** [comment]
Hey @devsnd, did you have time to look trough this. I'm quite suspecting jPlayer seeking issue. Maybe fix will be as simple as update jPlayer for cm? Thanks a lot!

**Comment by systems-rebooter** [comment]
Fix: 

{code}proxy_http_version 1.1;{code}

http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_http_version

**Comment by devsnd** [comment]
Hey @systems-rebooter thanks for the investigation! Could you please update the wiki, so that other people can find out how to setup their proxy?

**Comment by rajesh-battala** [comment]
Yes,  please share details on wiki it would be helpful

**Comment by 6arms1leg** [comment]
> Hey @systems-rebooter thanks for the investigation! Could you please update the wiki, so that other people can find out how to setup their proxy?

I added the fix in section "Troubleshooting".
