### ISSUE TITLE
CherryMusic not starting via cron and init script anymore under Debian Wheezy

### ISSUE THREAD

**Issue by blindpet** [devsnd/cherrymusic#568]
I am running cherrymusic and it was working a few weeks ago as a crontab. Now I get this error

`/usr/bin/env: python3: No such file or directory`

I noticed this in the main cherrymusic file, however it works fine with python /opt/cherrymusic

`#!/usr/bin/env python3`

It means bot the crontab and init.d method are no longer working.

Is cherrymusic no longer backwards compatible with python 2.7 and 2.6?

**Comment by blindpet** [comment]
I just tested and by adding #!/usr/bin/python to the top everything works again, can you add this line or does it break something else?

**Comment by blindpet** [comment]
Thanks @6arms1leg ping me when it's changed

**Comment by pando85** [comment]
It's working for me in python 2.7 and 3.4 and travis test show it working.

Could you paste your crontab and init.d methods? Probably I could help you.

**Comment by blindpet** [comment]
Here is what was working before

@reboot cd /opt/cherrymusic ; python cherrymusic

**Comment by pando85** [comment]
I think that it isn't a good practice. But I don't understand why don't work if your python -V shows 2.7 really...
Try using complete routes like this:
```bash
@reboot /usr/bin/python2 /opt/cherrymusic/cherrymusic
```

**Comment by blindpet** [comment]
Did that already, makes no difference

**Comment by pando85** [comment]
Why do not you use python3 to execute cherrymusic?
If you do:
```bash
python3 /opt/cherrymusic/cherrymusic
```
what error shows you?

**Comment by blindpet** [comment]
it works with both in the command line, i get the env error usr/bin/env: python3: No such file or directory. This was working before..

**Comment by blindpet** [comment]
I also don't want to use python3 if I can avoid it, everything I run is python 2.7

**Comment by pando85** [comment]
I think that it isn't a bug of cherrymusic anyway, probably it could be related about your enviroments variables, but I don't know, sorry.

**Comment by blindpet** [comment]
I think you're right, it could be environment variables. I made this issue because it must be possible to have cherrymusic work with python27 and 3 while not breaking backwards compatibility

**Comment by pando85** [comment]
But I still don't understand if you execute: ```/usr/bin/python2.7 /opt/cherrymusic/cherrymusic``` you cant getting it working.

**Comment by blindpet** [comment]
Me neither, it spits out the same env error in the init script when I use python2.7 without changing the cherrymusic file manually

**Comment by 6arms1leg** [comment]
Which GNU/Linux distribution are you using? (Does it happen to be s.th. Debian-ish?)
Did you do any system upgrades since it stopped working?
Which user are you using to set up the CherryMusic cron job?

Anyway, this doesn't seem to be a bug in CherryMusic, but rather a problem with your system configuration...

**Comment by blindpet** [comment]
On Debian 7 for arm, no upgrades to Jessie, still using Wheezy. The exact same guide I made a month or so ago was working, now it isn't.

Has nothing changed in the !#python line in the last month or two?

Many other python programs like SickRage, Headphones, CouchPotato etc all work fine and are using python 2.7 using cronjobs and init scripts, so there is definitely something different about CherryMusic..

**Comment by blindpet** [comment]
If there is a python 2.7 specific branch then I'll just use that, that env tag seems to be forcing python 3 which I do not want

**Comment by 6arms1leg** [comment]
I figured it was Debian – this distribution can be very picky about cron jobs and commands in /etc/rc.local.

> [...] no upgrades to Jessie, still using Wheezy.

No, I'm not talking about major release upgrades of Debian but any system/package upgrades (like in `# aptitude update && aptitude upgrade`).
Which user are you using to set up the CherryMusic cron job?

**Comment by blindpet** [comment]
All current updates as of today for Wheezy. The user for the cronjob is a pi user which has sudo rights. Not sure why this matters, like I said when I change the first line in the cherrymusic script it works again so I'm not sure what other proof you need.

Is adjusting that line a recent commit to the dev branch? Like I said the same exact gudie on the same distro worked a month ago, now users are complaining to me it's no longer working.

Even when I specify /usr/bin/python2.7 in the cronjob it exists with the env error which is clearly triggered by the first line in cherrymusic

**Comment by 6arms1leg** [comment]
> All current updates as of today for Wheezy.

So it might as well be caused by some Wheezy security upgrade...

> The user for the cronjob is a pi user which has sudo rights. Not sure why this matters [...]

So you are setting up your cron job with `$ sudo crontab -e`? It matters because that's really bad practice. CherryMusic – like any other server application – should never run as root! If that is in your guide, I recommend changing that as to not to compromise the security of your readers.

> Is adjusting that line a recent commit to the dev branch?

Please take a look at the [commit history](https://github.com/devsnd/cherrymusic/commits/devel/cherrymusic) of the `cherrymusic` file yourself.
[The shebang indeed has been changed](https://github.com/devsnd/cherrymusic/commit/682cbf913f06354a5b9a25fc1fd07f59283a3bd4), but that was over a year ago.

**Comment by blindpet** [comment]
No the crontab is running as the pi user, no sudo is involved at all.

Changing the shebang line makes everything work again so that will just be the procedure from now on if there will not be a python2.7 specific branch

Is there a reason you force the shebang line to be python3 instead of letting users specify which python version to run CherryMusic as?

**Comment by blindpet** [comment]
I managed to get some log output from the cronjob

Invalid basedir. Please provide a valid basedir path.
ue: u'None' (basedir must be absolute path: None)
[150601-01:06] ERROR   : ConfigValueError: invalid value: u'None' (basedir must be absolute path: None)

This is the current crontab

@reboot cd /opt/cherrymusic ; /usr/bin/python /opt/cherrymusic/cherrymusic >/opt/cherrymusic/logfile.txt 2>/opt/cherrymusic/logfile.txt

**Comment by pando85** [comment]
First of all, I think you can ommit ```cd /opt/cherrymusic``` in that configuration.
Probably, it's better for you to try the service script that it is in the wiki, but it can be related with a bad configuration of env vars. If you work with cherrymusic as a service well executed you only must do an:``` update-rc.d cherrymusic defaults``` and it will run at start. I have that configuration with a ubuntu 14.04 VM and it works perfect.

**Comment by blindpet** [comment]
Agreed pando, the error is the same no matter which python I try. The init.d script doesn't work either. I am not on Ubuntu but Debian. That init.d script from the wiki is not working for me. I have tried /usr/bin/python and /usr/bin/python2.7

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="CherryMusic"
NAME=cherrymusic
DIR=/opt/cherrymusic
DAEMON=$DIR/cherrymusic
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
PYTHON=/usr/bin/python2.7

I also set the user and group as pi since that is who owns the cherrymusic folder

the init.d script returns an ok but it doesn't work. I can get another init.d script to start the service manually but it doesn't work on boot. The half working script I adapted from here https://github.com/jasonblewis/sample-service-script

**Comment by blindpet** [comment]
Last thing I tried in the crontab was @reboot cd /opt/cherrymusic && /usr/bin/python cherrymusic. Also tried just python, same error as above

Invalid basedir. Please provide a valid basedir path.
ue: u'None' (basedir must be absolute path: None)
[150601-01:06] ERROR : ConfigValueError: invalid value: u'None' (basedir must be absolute path: None)

**Comment by pando85** [comment]
I don't think that doing that is necesary:
 ```bash
@reboot cd /opt/cherrymusic && /usr/bin/python cherrymusic
```
If your problem is related with configuration value , it could be because the program doesn't find configuration file because something is wrong with env variables. Try with this:
```bash
@reboot export XDG_DATA_HOME=/home/pi; /usr/bin/python /opt/cherrymusic/cherrymusic 
```
Does cherrymusic have an option to set the path of configuration file?
I think it doesn't and could be a good option for this kind of problems.

**Comment by 6arms1leg** [comment]
@blindpet, please start using markdown for better readability.

**Comment by blindpet** [comment]
I will try and remember the triple backtick, I'm used to other systems where I can highlight and click 'code', github should have something like that.

I tried @pando85 latest suggestion and it still didn't work. I am just explaining how to start manually at this point until I can specify a basepath.

**Comment by devsnd** [comment]
Hey @blindpet!

The python 2 support was added later to CM to support distributions like debian, which take ages to update their packages. The preferred way to run CM is to use python 3.

The problem about the shebangs is that many distros still use python 2 as default so `#!/usr/bin/env python` points to python 2 most of the time, even though we'd like most of our users to use python 3, so there are less problems when it comes to encodings etc.

I recommend just to let you crontab start CM explicitly using python 2, e.g. `/usr/bin/env python2 /path/to/cherrymusic` to circumvent that issue. Also: please feel free to update the wiki to help other users that run debian 6, if that fixes your problem.

**Comment by tilboerner** [comment]
Don't know if anybody noticed: At some point the problem changed. It started out with `/usr/bin/env: python3: No such file or directory`, and now it seems we're at:

```
Invalid basedir. Please provide a valid basedir path.
ue: u'None' (basedir must be absolute path: None)
[150601-01:06] ERROR : ConfigValueError: invalid value: u'None' (basedir must be absolute path: None)
```

This means that the `cherrymusic` script is being executed. However, it's using the default configuration, where basedir is given as `None`. This value is set in `cherrymusic.conf`, which the program expects to find in `$HOME/.config/cherrymusic/`. Of course, the exact directory depends on which user is running the process.

@blindpet, could you please check if:

- crontab is running the script as the user you expect it to,

- CherryMusic uses the right configuration directory for this user 

        $ sudo -u <USERNAME> python cherrymusic --info

- this directory contains a properly configured `cherrymusic.conf` (check file contents, CherryMusic creates a default file by itself).

**Comment by blindpet** [comment]
Thank you @tilboerner this was exactly the kind of info I needed. I will test it sometime soon and report back

**Comment by blindpet** [comment]
I just wanted to close this, it turned out the script I made was running the initial setup as root so the baseconf wasn't there, adding sudo -u user python /opt/cherrymusic/cherrymusic --setup and now the configuration is in the right directory for the cronjob.

Thank you all for your help in resolving this.
