### ISSUE TITLE
eclipse errors when imported to eclipse

### ISSUE THREAD

**Issue by rajesh-battala** [devsnd/cherrymusic#576]
Hi All, 
Am interested to contribute to cherrymusic, I have tried playing with cherrymusic its Awesome!.
I want to contribute to the project, I have done git clone and got the project into eclipse. But Am getting lots of errors in py-dev. almost all are import errors.
Can anyone please guide how to import to eclipse or which IDE developer uses to code cherrymusic.
Thanks

**Comment by devsnd** [comment]
Hi @rajesh-battala!

I have no experience using Eclipse for a python or javascript project, so I cannot help you to set it up. Personally I'm using sublime text or pycharm, which work nicely for the task.

If you have any specific questions feel free to reopen the bug.
