### ISSUE TITLE
How many users can CherryMusic handle?

### ISSUE THREAD

**Issue by rajesh-battala** [devsnd/cherrymusic#577]
Hi All, 
Am Happy to see CherryMusic project.
you people are awesome and created such a great project.
I have started using it on my local box and it works superb!.

I want to deploy CherryMusic as streaming server in our intranet so that we can share all our music at one place.

I would like to know, how many users can start streaming at a time from CherryMusic.
Please let me know recommendations about how can I deploy for users around 500 -1000

**Comment by 6arms1leg** [comment]
Hello @rajesh-battala,

nice to hear that you like CherryMusic! And I'm really excited about your plans to deploy CherryMusic in your intranet to such a huge user base!
Actually, we ourselves have tested CherryMusic with only about 15 users. So frankly, we don't know yet how CherryMusic will perform in such a case. My guess is that CherryMusic itself will perform reasonably well and that the critical part is not with CherryMusic but with your hardware:

* Can your Intranet bandwidth handle up to ~1000 users streaming music?
If this is the bottleneck you can allow (or force) transcoding to a format with high compression and which is optimized for streaming (e.g. Opus). This, however, increases your server load, which brings me to the next point:

* Can your server hardware handle up to ~1000 users streaming (and potentially transcoding) music?
The server load can be reduced, by turning CherryMusic's transcoding feature off, which on the other hand increases the bandwidth usage (if the file format of your music collection is not optimized for streaming).

That's the trade-off.
If you struggle with both, you could encode your whole audio collection to a streaming-friendly file format and index that new encoded collection with CherryMusic, turning it's transcoding feature off – admittedly, not the most elegant solution.

**Comment by rajesh-battala** [comment]
Thanks a lot for your views and suggestions.
I will discuss your points with my admin.


On Sun, Jun 21, 2015 at 6:21 PM, 6arms1leg <notifications@github.com> wrote:

> Hello @rajesh-battala <https://github.com/rajesh-battala>,
>
> nice to hear that you like CherryMusic! And I'm really excited about your
> plans to deploy CherryMusic in your intranet to such a huge user base!
> Actually, we ourselves have tested CherryMusic with only about 15 users.
> So frankly, we don't know yet how CherryMusic will perform in such a case.
> My guess is that CherryMusic itself will perform reasonably well and that
> the critical part is not with CherryMusic but with your hardware:
>
>    -
>
>    Can your Intranet bandwidth handle up to ~1000 users streaming music?
>    If this is the bottleneck you can allow (or force) transcoding to a
>    format with high compression and which is optimized for streaming (e.g.
>    Opus). This, however, increases your server load, which brings me to the
>    next point:
>    -
>
>    Can your server hardware handle up to ~1000 users streaming (and
>    potentially transcoding) music?
>    The server load can be reduced, by turning CherryMusic's transcoding
>    feature off, which on the other hand increases the bandwidth usage (if the
>    file format of your music collection is not optimized for streaming).
>
> That's the trade-off.
> If you struggle with both, you could encode your whole audio collection to
> a streaming-friendly file format and index that new encoded collection with
> CherryMusic, turning it's transcoding feature off – admittedly, not the
> most elegant solution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/devsnd/cherrymusic/issues/577#issuecomment-113897270>.
>



-- 
Thanks
Rajesh Battala

**Comment by systems-rebooter** [comment]
Good point @rajesh-battala !

On 2 points @6arms1leg described - I stucked with first one with bandwidth limiting technic (its pretty much calculable how many users you can handle once knowing a) connection throughput b) major % of tracks encoded with XYZ kbps bitrate). While tested option 2 i noticed that while transcoding 1 song lame occupies 1 CPU core 100% Also transcoding can be discarded by user in his account -  see #535

If sound quality is not the case you can simply transcode you collection to lower bitrate as  @6arms1leg suggested, but remember that lossy --> lossy conversation to XYZ bitrate  always degrades sound quality more then direct lossless --> lossy XYZ bitrate. 

Unfortunately i can't answer you major question - How many users can CherryMusic handle?, since my project is not live yet. But once it will - i will share numbers and culprits here. 

Thanks!

**Comment by rajesh-battala** [comment]
Thanks @systems-rebooter
