### ISSUE TITLE
Is there a good android client for CherryMusic?

### ISSUE THREAD

**Issue by Dechcaudron** [devsnd/cherrymusic#587]
Hey there, I was wondering if I can get some Android client that I can set up to connect to my server so I don't have to use a web browser to listen to my music. If there is not, perhaps we should make one ;)

**Comment by Konubinix** [comment]
@Dechcaudron: I think you should take a look at #495.
I use a client called Cherry. I could not say it is good since it is only a wrapper around the web view and it is quite slow but it works.

**Comment by Dechcaudron** [comment]
thanks, @Konubinix, I might give it a try :smiley:
