### ISSUE TITLE
Configuration Question

### ISSUE THREAD

**Issue by samyoungnyc** [devsnd/cherrymusic#591]
Awesome product, thanks! My question is - is it possible to configure CherryMusic so that it acts as a streaming radio on a site which anyone can access?

**Comment by 6arms1leg** [comment]
Hello @samyoungnyc,

no, the use case you described is not within the scope of CherryMusic. It is not meant to be used as an internet radio.
CherryMusic is developed to handle huge audio collections and serve them over a web interface, where users can log in, create, share and listen to playlists – much like your personal Spotify.

To set up a simple internet radio, you might have a look at [Icecast](http://www.icecast.org/) and/or [MPD](http://www.musicpd.org/) (newer versions of MPD have streaming capabilities).

Thanks for checking out CherryMusic, though!

**Comment by samyoungnyc** [comment]
OK I understand - I checked out MPD and Icecast but the documentation isn't as clear. I was hoping Cherrymusic would have this option because it work's so well... oh well! Thanks, it's an awesome program and I'll be using it anyhow.

**Comment by 6arms1leg** [comment]
You are right, documentation on MPD isn't that great. But actually, using MPD (standalone) for basic audio streaming is quite simple. (I don't know about Icecast, though. Never used it.)
Add the following to your `/etc/mpd.conf`: 

```
### httpd output (built-in http streaming server) ###
#
audio_output {
       type            "httpd"
       name            "http stream"
       encoder         "lame"                # optional, vorbis or lame
       port            "8000"
#       quality         "5.0"                   # do not define if bitrate is defined
       bitrate         "128"                   # do not define if quality is defined
       format          "44100:16:1"
}
```

Now restart MPD for changes to take effect. On Debian that would be:

```
$ sudo service mpd restart
```

Done. You can access you stream under ```YOUR_IP:8000```.
Hope that helps to get you started...

**Comment by samyoungnyc** [comment]
Thanks for the help!

**Comment by bfg9000d** [comment]
If you want other people to be able to control it using a nice web interface, maybe take a look at [groovebasin].

[groovebasin]: https://github.com/andrewrk/groovebasin

**Comment by samyoungnyc** [comment]
Hmm seems interesting, I'll take a look. At this point I'm thinking of hacking on MPD/Icecast etc and creating an extremely simple (much simpler than Cherrymusic or groovebasin) desktop app out of it.
