### ISSUE TITLE
share specific folder/playlist to a specific user

### ISSUE THREAD

**Issue by mmkhouri** [devsnd/cherrymusic#592]
hey guys, 
first of all, thanks for such an amazing program!

I was wondering if is there a way to share ONLY a specific Playlist/Folder to a specific User Account that I created in CM? so then the user can't see the other playlists/songs

Example:
folder /Metallica/ only shared to user X 
folder /Iron Maiden/ only shared to user Y 
folders /Metallica/ & /Iron Maiden/ only shared to user Z 

thanks!

**Comment by 6arms1leg** [comment]
Hello @mmkhouri,

no, currently we don't have such a detailed permissions management for directories/audio files. All directories/audio files are accessible by all users.
For playlists, you can choose between "public" and "private", making them visible to all users or none.

We know, that's pretty basic, but (e.g.) a Unix-like permissions management (even without write-permissions, as CherryMusic will never make changes to your music collection) adds quite a layer of complexity.
Currently, CherryMusic is in a state of rewrite, so it might take some time until this feature will be considered.

I hope you enjoy CherryMusic anyway!

**Comment by devsnd** [comment]
Hello @mmkhouri,

Sorry, but this will feature will never be added to CherryMusic. CherryMusic is about trust: you are giving away a key to your complete music collection to friends and family.

You can however start multiple CM servers each on a different port and with a different configuration  e.g. a different basedir (this requires one *nix user per server). You can also use symlinks within the basedir to compose a basedir from multiple locations (note: symlinks only work in the basedir, but are ignored on any other level to avoid possible security risks and cyclic folder structures)

Thanks for the suggestion though! See you next time. :car: :cactus:
