### ISSUE TITLE
getResourcePath() should skip share and local/share search on Windows

### ISSUE THREAD

**Issue by alexandrul** [devsnd/cherrymusic#594]
On Windows, `sys.prefix` is the root of the installed interpreter, so `share` and `local/share` subfolders are not found, and should be skipped.

Sample search locations:
```
D:\CherryMusic\Python\share\cherrymusic\res/i18n
D:\CherryMusic\Python\local\share\cherrymusic\res/i18n
D:\cherrymusic\cherrymusic\res/i18n
```

Environment:
* Win 7 x64
* Python 3.5.0 x64
* head of `devel`

**Comment by devsnd** [comment]
Hi Eduard-Cristian!

Thanks for you bug report! Would you be willing to create a pull request with the appropriate changes? I'd be happy to merge it. you could check for `sys.platform.startswith('win')` to find out if it's a windows machine.

**Comment by alexandrul** [comment]
I will give it a shot this weekend
