### ISSUE TITLE
Can't see .oga Files

### ISSUE THREAD

**Issue by Espionage724** [devsnd/cherrymusic#597]
Hi, I recently set-up CherryMusic on Fedora 23 Server with this guide: https://gitlab.com/Espionage724/Linux/blob/master/Servers/CherryMusic-git.txt

I tossed my music library over with various mp3, oga, and flac content. The mp3 and flac files appear and play fine, but the oga files don't show in CherryMusic's interface to play. The media library updater seems to see them though.

This isn't the entire list of files, but here's a few filenames for the oga files I have: http://pastebin.com/QRHH9mCq

Edit: Renaming a file from .oga to .ogg shows the file and allows for playback; so perhaps CherryMusic can't see .oga files because it doesn't know how to look for them?

**Comment by devsnd** [comment]
Hey Sean,

thanks for the report! I have added decoder support for files with the oga ending. Check out the `devel` branch to try it out until the change gets into the next release.

have a nice day!
