### ISSUE TITLE
Run cherrymusic on an shared hosting server

### ISSUE THREAD

**Issue by Benedikt1992** [devsnd/cherrymusic#606]
cherrymusic is a great to share and stream my music.

Unfortunately I've only a shared hosting server (I am able to run cgi scripts including python). Therefor I can't start cherrymusic as an own process and own  port. Is there a way to embed cherrymusic in a web server (vhost) with a cgi-script?

**Comment by devsnd** [comment]
Hi Benedikt,

Sorry but this not possible; The server then would have to start up and shut down for every request, which won't work very well. Apart from that, there is AFAIK no necessary state of the program saved in memory for it to work (everything is in the database or in a file, so you might be able to get it to run if you hack around a bit. [Here's a bit of information about cherrypy (the server framework powering cherrymusic) running CGI](http://tools.cherrypy.org/wiki/RunAsCGI), but it does not look too promising...
