### ISSUE TITLE
USB HDD Stored Music

### ISSUE THREAD

**Issue by JDNooB** [devsnd/cherrymusic#608]
I have my music stored on a USB external hard drive plugged directly into the RPi. 
Having gone into cherrymusic setup for the first time I need to point it to the music.
Do I need to mount the USB drive or will it just read from the location?

I am also having a hard time working out the format of the address for the USB drive to input
my HDD is a WD Elements should the address be something like
/dev/sda1/elements/Music

any and all help appreciated.
thanks

**Comment by 6arms1leg** [comment]
Hey @JDNooB !

Sorry for the late response.
It's great to hear that you like CherryMusic and (learn to) use GNU/Linux. Please don' get me wrong, but this issue tracker here at CherryMusic's project page on GitHub is not the right place to ask basic GNU/Linux questions.
But to answer your question first:
Yes, to be able to read from a HDD you need to mount it first. The exact steps for this procedure depend on many aspects (e.g. HDD filesystem, Linux distribution, desktop environment installed, etc.).
If you have a desktop environment running, your external HDD is probably mounted automatically. The manual steps in general are:
* Plug in your external HDD
* run `dmesg` and/or `fdisk -l` to determine under which device name your HDD registered (and which fs it has)
* create a mount point (= empty directory) with `mkdir MOUNTPOINT`, where "MOUNTPOINT" is the path to the directory where your HDD will be mounted
* mount your HDD with `mount DEVICENAME MOUNTPOINT`, where "DEVICENAME" is the path you obtained from the 2nd step and "MOUNTPOINT" is the path to the directory where your HDD will be mounted

Step 2 and 4 probably need root access.

The process above sounds more complicated than it is. Please use [an internet search engine](https://duckduckgo.com/?q=linux+mount+external+hdd&ia=qa) for more details.
If you are unsure how to use a command, e.g. the `mount` command, run `man mount` for help.

But to sum up what I initially wanted to say:
* From now on, please use an internet search engine to answer basic Linux questions. If you have specific questions concerning CherryMusic, feel free to continue to ask them here.
* For a basic setup of CherryMusic, please check out our [wiki page](https://github.com/devsnd/cherrymusic/wiki/Setup-guide)
* The command `man COMMAND` often helps, try for example `man man`

Hope that helps. Have fun with Linux!
