### ISSUE TITLE
Cherry Music initial setup

### ISSUE THREAD

**Issue by JDNooB** [devsnd/cherrymusic#609]
hi
Following help from other users here I got my install to the initial setup via localhost:8080 it out as I couldnt progress because I was unable to provide the music library address (separate issue)
Now I cant get back on to the localhost:8080 I just get a web page unavailable.

back on the pi if I try to rerun the setup port it fails:

volumio@volumio:~$  python cherrymusic --setup --port 8080
python: can't open file 'cherrymusic': [Errno 2] No such file or directory
volumio@volumio:~$  python cherrymusic setup port 8080
python: can't open file 'cherrymusic': [Errno 2] No such file or directory
any thoughts?

**Comment by systems-rebooter** [comment]
Hi @JDNooB 

Due to error, you need to issue the command from cherrymusic installation folder. Please issue `cd /cherrymusic/installation/folder` first and rerun setup command.

**Comment by JDNooB** [comment]
Hi, thanks.
 s
It doesn't hink I have a cherrymusic folder - but I was in the browser setup screen this morning...
Should I reformat and start from scratch??

Volumio Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Jan 14 15:14:34 2016 from 192.168.0.7
volumio@volumio:~$ cd /cherrymusic/installation/folder
-bash: cd: /cherrymusic/installation/folder: No such file or directory

**Comment by 6arms1leg** [comment]
Hello @JDNooB ,

OK, same general recommendations as I mentioned in #608 apply here. This is basic GNU/Linux knowledge which you have to learn on your own. I know there is a steep learning curve – especially at the beginning. If you want a running CherryMusic server and learn some of these basics on the go, you should really try one of the guides in our [wiki page](https://github.com/devsnd/cherrymusic/wiki/Setup-guide). If you exclusively run CherryMusic on your RPi (and nothing else), I recommend to install standard Raspbian and follow [this step by step guide](http://fomori.org/blog/?p=687). In this guide, every single step is explained and you will end up with a correctly and safely running CherryMusic server.

About the solution @systems-rebooter posted:
`/cherrymusic/installation/folder` is just a placeholder. You have to replace it with the correct path to your CherryMusic directory.
