### ISSUE TITLE
cherrymusic.conf file is resetted after reboot on Qnap TS-251

### ISSUE THREAD

**Issue by mapomme1108** [devsnd/cherrymusic#614]
Hello,

I have installed Cherrymusic, on my Qnap TS-251. It works but
the configuration file (cherrymusic.conf) is resettted after each reboot.

I have to do again the configuration of Cherrymusic after each reboot.

How can I solve that problem?

**Comment by mapomme1108** [comment]
I think I have found a workaround by adding arguments to the start command line.

I do it that way :
cherrymusic --update /share/Multimedia/Musique --adduser admin xxxx --port xxxx

But I have a message telling me that the path to the folder in which the music is not correct

**Comment by 6arms1leg** [comment]
Seems to be not an issue anymore...(?)

**Comment by mapomme1108** [comment]
I have finally installed CherryMusic on a Debian in QVM
