### ISSUE TITLE
Songs stopping early

### ISSUE THREAD

**Issue by dcroxton** [devsnd/cherrymusic#615]
I just discovered CherryMusic and I love it.  It works beautifully out of the box.  Except...I am having a sporadic problem with my songs cutting off early.  Sometimes when I am playing an album, one song will stop, usually about 80% through, and it will jump to the next track in the playlist.  It doesn't always do this, just sporadically.  It seems to happen more when I am accessing it through a remote device (my tablet, still on the local network) than localhost.

I don't see any logging built in.  I have been piping the output to a file, but the only error I see is the "session was saved without being locked," which happens regardless of whether the songs are being truncated or not.  These are all flac-encoded songs, BTW.

**Comment by furieuxjk** [comment]
+1
I have the same problem with FLAC files.

**Comment by diomekes** [comment]
Same problem, using the devel Archlinux package. Doesn't seem to happen with mp3, only FLAC, from my short tests.

**Comment by portaloffreedom** [comment]
Also for me happened a couple of times in one day usage, with FLAC songs.
Could it be that the error is somewhere in the live transcoding code?

**Comment by tripleFA** [comment]
Same problem here on Debian with FLAC songs

**Comment by 6arms1leg** [comment]
Hello there,

sorry to hear that! That's an annoying issue.

> Could it be that the error is somewhere in the live transcoding code?

Probably. And we already have an issue for that (#599), where transcoded flac and m4a files are also reported to cause the problem. So I will close this one as a dublicate. Please subscribe to above mentioned issue to stay updated and continue the conversation there.
