### ISSUE TITLE
Error: redirection to https when http port is 80 returns "500. Internal server error"

### ISSUE THREAD

**Issue by bigb123** [devsnd/cherrymusic#616]
There is problem with redirection to "ssl_port" when port 80 is default cherrymusic port and you wont type port number with url.

# Error log

```
[160229-23:00] ERROR   : [29/Feb/2016:23:00:39] HTTP
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/cherrypy/_cprequest.py", line 670, in respond
	response.body = self.handler()
File "/usr/local/lib/python3.4/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
	self.body = self.oldhandler(*args, **kwargs)
File "/usr/local/lib/python3.4/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
	return self.callable(*self.args, **self.kwargs)
File "/home/serwouser/cherrymusic/cherrymusicserver/httphandler.py", line 141, in index
	self.getBaseUrl(redirect_unencrypted=True)
File "/home/serwouser/cherrymusic/cherrymusicserver/httphandler.py", line 132, in getBaseUrl
	ip = ipAndPort[:ipAndPort.rindex(':')]
ValueError: substring not found
```
Web browser will say: "500. Internal server error"

# Environment:

```
OS: Debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux
Browser: Mozilla Iceweasel 38.6.1
Interpreter: Python 3.4.2
CherryPy: 5.0.1
pyOpenSSL: 0.15.1
```

# How to reproduce:

1. In "cherrymusic.conf" file set values: 

 - "port = 80", 

 - "ssl_enabled = True"

 - "ssl_port = 8443" (you can use any free port other than 80)

2. Generate or use existing ssl certificate and ssl key (remember to put their paths to config file).

3. Run cherrymusic (you probably need to run it as root or administrator).

4. Try to open webpage with your cherrymusic without typing port number (eg: "192.168.0.16" not "192.168.0.16:80"). Webpage will crash with "500. Internal server error" in browser and with error mentioned above in console.

# Reason:

In "cherrymusicserver/httphandler.py" line 132 breaks the program:

    ip = ipAndPort[:ipAndPort.rindex(':')]

Variable "ipAndPort" carries "192.168.0.16" string, not "192.168.0.16:80". Function "rindex" cannot find colon ":" sign and returns "ValueError" when substring is not found ([rindex documentation] (https://docs.python.org/3.4/library/stdtypes.html?highlight=rindex#str.rindex)). 

This probably comes from wrong assumption that function "parse.urlparse(cherrypy.url()).netloc" in this same file in 126. line will return host address with port number. However, you can run your cherrymusic web page without specifying port number because 80 is the default one.

# Workaround:

You can put the line:

    ip = ipAndPort[:ipAndPort.rindex(':')]

in try-except block. Works for me. Diff below.

# My diff:
```
diff --git a/cherrymusicserver/httphandler.py b/cherrymusicserver/httphandler.py
index 11aa25c..c3ab0a1 100644
--- a/cherrymusicserver/httphandler.py
+++ b/cherrymusicserver/httphandler.py
@@ -128,7 +128,10 @@ class HTTPHandler(object):
         ssl_enabled = cherry.config['server.ssl_enabled']
         if ssl_enabled and not is_secure_connection:
             log.d(_('Not secure, redirecting...'))
-            ip = ipAndPort[:ipAndPort.rindex(':')]
+            try:
+                ip = ipAndPort[:ipAndPort.rindex(':')]
+            except ValueError:
+                ip = ipAndPort
             url = 'https://' + ip + ':' + str(cherry.config['server.ssl_port'])
             if redirect_unencrypted:
                 raise cherrypy.HTTPRedirect(url, 302)
```

**Comment by 6arms1leg** [comment]
Hello @bigb123 ,

thanks for your detailed report!
Two things I want to comment on:

> Run cherrymusic (you probably need to run it as root or administrator).

Never run CherryMusic (or any other server application) as root!

> [...] and you wont type port number with url.

AFAIK, CherryMusic is meant to be accessed in the browser **with** specifying the port explicitly.

Well, let's wait and see what @devsnd and @tilboerner have to say...

**Comment by bigb123** [comment]
Hi @6arms1leg, 

thanks for your interest!

> Never run CherryMusic (or any other server application) as root!

It's true, however, I am sometimes connected to public filtered network where you can connect only to ports 443 and 80. Running it by root is my poor workaround (I understand the potential security risk) but it works. Hope that one day new version will give me ability to run it on ports <1024 without root privileges.

Maybe better solution is to run cherrymusic with nginx proxy?

> CherryMusic is meant to be accessed in the browser with specifying the port explicitly.

Because it is not meant to run on default http port, which need root privileges :)

**Comment by 6arms1leg** [comment]
> Maybe better solution is to run cherrymusic with nginx proxy? [...] Because it is not meant to run on default http port, which need root privileges :)

I don't have much experience with Nginx, sorry.
But to run CherryMusic (or any other server application) on a port<1024 without root you could just use iptables for a port redirect. See [this](https://serverfault.com/questions/268099/bind-to-ports-less-than-1024-without-root-access) for example. That would be far better security-wise.

Now, does the HTTPS redirect work correctly, when you specify the port (`:80`) in the URL explicitly (even though you normally wouldn't since you are on the default port)?

**Comment by bigb123** [comment]
>  to run CherryMusic (or any other server application) on a port<1024 without root you could just use iptables for a port redirect

It is good idea. Didn't think about it before.

> Now, does the HTTPS redirect work correctly, when you specify the port (:80) in the URL explicitly (even though you normally wouldn't since you are on the default port)?

"http://my_address:80" redirects properly to https page
"http://my_address" throws an error mentioned above

**Comment by 6arms1leg** [comment]
Just a side note: I added a section "Bind CherryMusic to ports less than 1024 (without root access)" to the [tips and tricks section of our wiki](https://github.com/devsnd/cherrymusic/wiki/Setup-guide#tips-and-tricks).

And for the initial issue about the special case of port 80 I think you are right, since one would expect it to work without specifying the port.

**Comment by devsnd** [comment]
Hello Piotr!

Thanks for your very detailed bug report and fix! Have a piece of cake: :cake: 

The fix is now included in the devel branch! Have a nice day and see you around.
