### ISSUE TITLE
Failed to load file browser (Ubuntu 14.04)

### ISSUE THREAD

**Issue by mapomme1108** [devsnd/cherrymusic#618]
Hello,
I have installed CherryMusic on Ubuntu 14.04 on a Raspberry Pi

I have created a script to run CherryMusic at reboot.
When I run the script manually : it works
When the script is executed automatically at startup : there is an error message in CherryMusic when I click on "Browse Files", the message is : "Failed to load file browser"

How can I fix it?

Thanks per advance for your help.

**Comment by 6arms1leg** [comment]
Hello @mapomme1108 ,

well, then it would be easier if we could see what's in the script, its permissions and how it is executed at boot.
Without those information I could only have a guess that is has something to do with permissions (maybe CherryMusic is run by the wrong user when it is executed in the script?).

**Comment by mapomme1108** [comment]
Hello @6arms1leg 
Thank you for answering but I installed CherryMusic on Debian and it works
