### ISSUE TITLE
Debian : FFmpeg for m4a support

### ISSUE THREAD

**Issue by mapomme1108** [devsnd/cherrymusic#620]
Hello,

I would like to know how to install and use ffmpeg instead of the others codecs on Debian.

Because I want to be able to m4a audio files.

Thanks

**Comment by devsnd** [comment]
hey mapomme,

you just need to install the ffmpeg package.

    apt-get install ffmpeg

ffmpeg is already the preferred decoder for m4a files. after installing you have to restart the server so that cherry music detects the available codecs.

**Comment by mapomme1108** [comment]
Thanks.
I use Debian Jessie so I will have to compile it myself because 
apt-get install ffmpeg
does not work.

**Comment by mapomme1108** [comment]
I have installed both ffmpeg and the others codecs and it works!

But I have no progress bar with Flac and m4a

**Comment by mapomme1108** [comment]
How can I fix the problem with the progression bar?

**Comment by 6arms1leg** [comment]
Hey @mapomme1108 ,

great to hear that it works for you now!
The progress bar problem is a known (and still open) issue (see #275). Somewhere down the comments @devsnd gives a detailed explanation about the problem, if you want to know more.
