### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by SpiraFax** [devsnd/cherrymusic#621]
Running on a RPI,

I had cherry music working then something when wrong with the system and some packages got un-installed. now Cherry music won't launch instead seeing the print out:

          $ python3.4 cherrymusic
          Traceback (most recent call last):
            File "cherrymusic", line 236, in <module>
              cherrymusicserver.start_server(ConfigOptions.configdict)
            File "/opt/cherrymusic/cherrymusicserver/__init__.py", line 259, in start_server
              CherryMusic(cfg_override)
            File "/opt/cherrymusic/cherrymusicserver/__init__.py", line 320, in __init__
              CherryMusic.create_pid_file()
            File "/opt/cherrymusic/cherrymusicserver/__init__.py", line 348, in create_pid_file
              os.getpgid(int(pidfile.read()))
          ValueError: invalid literal for int() with base 10: ''
          $

I have wiped and cloned and built and installed cherrymusic again and the same error, updated everything including python and still the same problem. 

I can run the setup page.

**Comment by 6arms1leg** [comment]
> [...] something when wrong with the system and some packages got un-installed.

That's a very vague description. What "went wrong"? What GNU/Linux are you running? Almost all distributions have some kind of logging system, where you can trace back what happened and in your case, which packages exactly got uninstalled. Did you reinstall all of them?

Do you have the file `~/.local/share/cherrymusic/cherrymusic.pid`? If so, delete it:
`$ rm  ~/.local/share/cherrymusic/cherrymusic.pid`
and try starting CherryMusic afterwards.

**Comment by SpiraFax** [comment]
Ah yes thank you so much!
I was looking for a lock file but obviously couldn't find it. 

It was vague because the i consider it a solved issue. The problem was my root partition got filled up and I then i ran a apt-get auto-remove to get some space back but i guess that wasn't the problem was.

**Comment by Musikolo** [comment]
If you're fed up with this issue, you might be interested in this solution:
- https://wiki.archlinux.org/title/CherryMusic#CherryMusic_does_not_start_after_unclean_shutdown
