### ISSUE TITLE
Speed up the loading of folders

### ISSUE THREAD

**Issue by mapomme1108** [devsnd/cherrymusic#623]
Hello,

I have a large music collection and want to know if there is a way to speed up the loading of folders which contain many subfolders or songs.

For example, I have a folder with 100 subfolders and it takes a long time to load it in CherryMusic interface.

Thanks.

**Comment by 6arms1leg** [comment]
CherryMusic was initially designed to handle huge audio collections while keeping a small footprint and we consider the handling of directories to be quite fast.
Have a look at your `~/.config/cherrymusic/cherrymusic.conf`.
In your case, there are three options that affect how fast things are displayed in the browser interface, especially:

```
; MAXSHOWFILES specifies how many files and folders should be shown at the same
; time. E.g. if you open a folder with more than MAXSHOWFILES, the files will be
; grouped according to the first letter in their name. 100 is a good value, as a
; cd can have up to 99 tracks.
;
maxshowfiles = 100
```

You could also try to disable the display of album art:

```
; Tries to fetch the album cover from various locations in the web, if no image is
; found locally. By default it will be fetched from amazon. They will be shown
; next to folders that qualify as a possible album.
;
fetch_album_art = False
```

Finally, to speed up the search you can change this value:

```
; MAXRESULTS sets the maximum amount of search results to be displayed. If
; MAXRESULTS is set to a higher value, the search will take longer, but will also
; be more accurate.
;
maxresults = 20
```

Hope, this helps.
