### ISSUE TITLE
Directory name within 0.36.0 tarball does not conform to previous pattern, confusing ebuild

### ISSUE THREAD

**Issue by ajmac** [devsnd/cherrymusic#627]
The directory contained in the tar.gz for 0.36.0  is named "devsnd-cherrymusic-e2438a7" rather than cherrymusic-0.36.0

This is a problem for automated building on Gentoo or elsewhere as the ebuild expects cherrymusic-versionnumber

**Comment by 6arms1leg** [comment]
Hello @ajmac,

sorry, but I can't confirm this. I tried all recent [releases, both *.zip and *.tar.gz files](https://github.com/devsnd/cherrymusic/releases) and it works just fine: All extract to a directory named `cherrymusic-0.xx.0`.
Can you please try again (maybe on a different device) and see if the issue persists?
Maybe it was some temporary issue with GitHub. Creating the archive of a release is a mainly automated process, that GitHub takes care of – we don't create the archives manually.

**Comment by ajmac** [comment]
Ah, I see the difference - I actually downloaded from the main link on http://www.fomori.org/cherrymusic/Download.html which has a different tarball to the one on github.  Strange!

You're right, the github tarball is perfect.  Thanks for the response, I've been looking for a replacement for Sockso since development has stopped and I think cherrymusic is the one...

**Comment by 6arms1leg** [comment]
Great to hear that! Thanks for considering CherryMusic.
