### ISSUE TITLE
Cherrymusic doesn't work with python-cherrypy-6.0.2

### ISSUE THREAD

**Issue by Musikolo** [devsnd/cherrymusic#630]
Hi,

I have upgraded my system packages which upgraded to python-cherrypy to version 6.0.2. Then, I restarted cherrymusic and it refused to start up. It showed the following message:

>         CherryMusic needs the module "cherrypy" to run. You should install it
        using the package manager of your OS. Alternatively cherrymusic can
        download it for you and put it in the folder in which currently
        CherryMusic resides.
Download cherrypy now? (y/n)

So, I reverted back to the previous python-cherrypy package version 5.4.0 I had, it everything has worked again.

So, my guess is that cherrymusic needs an update to support the new version.

Thank you!

P.S: I cannot miss the chance to thank you for the great work you are doing. Awesome!!

**Comment by 6arms1leg** [comment]
Hello @Musikolo,

great to hear that you enjoy CherryMusic, so thanks for the motivation!
Which CherryMusic branch are you running – `devel` or `master`?

I received a similar error report about CherryPy yesterday, which also includes a simple fix – a missing new dependency (see the latest comment):
https://aur.archlinux.org/pkgbase/cherrymusic-devel-git/
Please try to install `python-six` and report back if this fixes the problem.
Thanks for your support!

**Comment by Musikolo** [comment]
Hi 6arms1leg,

I'm using master, and yes, you are absolutely right. After installing python-six, the issue is gone and everything works nicely again.

Thank you!

**Comment by devsnd** [comment]
Hey Musikolo,

Thanks for the report. CherryPy seems to have introduced a dependency on python-six from version >= 6.

I wonder however how you got to the situation to have cherrypy 6 installed without having six installed? You should report the missing dependency to the package maintainer of cherrypy of your distribution. (If it's arch, it seems to be fixed already)

**Comment by Musikolo** [comment]
Yes, it was Arch and I faced wit the issue before they fixed it. 

Now, everything is working great!
