### ISSUE TITLE
cherrymusic windows 

### ISSUE THREAD

**Issue by tylerhoot** [devsnd/cherrymusic#637]
cherrymusic will not detect ffmpeg if i put it in the directory with it or am i not installing ffmpeg so cherry music can find it. i cannot find a spot on the wiki to tell me how cherry music wants ffmpeg installed.

**Comment by devsnd** [comment]
Hey Tyler,

ffmpeg must be installed so, that it is inside the `path` environment variable of your shell. e.g. if you open `cmd.exe`, you should be able to launch `ffmpeg` from any location.

This article describes how to add a folder to your path:
http://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/

In your case you need to add the folder in which ffmpeg.exe resides to your path.

**Comment by tylerhoot** [comment]
thank you that fixed it could you put that in the page about setting up cherymusic in windows?
