### ISSUE TITLE
Truncated and out of sequence messages

### ISSUE THREAD

**Issue by skanduru** [devsnd/cherrymusic#639]
Hello,

I have setup CherryMusic-0.38.0 in a sandbox, started the server and snooped the packets.  I noticed the following issues which looked a bit odd to me. Please clarify if this is a known issue or if it has been fixed.

1. Truncated messages for getuserotions() getconfiguration() (I suppose) [ pkt seq 224, 225]
2. Out of sequence messages (Req or resp). please inspect the packets from pkt seq 118

Req /res/templates/mediabrowser-file.html
Req /res/bootstrap3/fonts/glyphicons-halflings-regular.woff
Req /res/templates/mediabrowser-compact.html
Req /res/templates/mediabrowser-message.html
Req /res/templates/mediabrowser-playlist.html
Req /res/templates/flash-message.html

Resp: glyphicons-halflings-regular.woff
Req /res/img/favicon32glow.png
Resp: favicon32glow.png
Req /res/img/cherrymusic_loader.gif
Resp: cherrymusic_loader.gif
Req /res/img/progress-bars.gif
Resp progress-bars.gif

Resp mediabrowser-compact.html
Resp mediabrowser-message.html
Resp mediabrowser-file.html
Resp flash-message.html
Resp mediabrowser-playlist.html

Unable to upload a zipped pcap file.  Is there anyway I can send it ?

Thanks,
Srini

**Comment by skanduru** [comment]
Seeing the message like this ... (per wireshark)

                        [truncated]{"data": {"username": "samu", "isadmin": 1, "version": "0.38.0", "getdecoders": ["opus", "mp3", "flac", "wav", "wma", "m4a", "oga", "ogg"], "fetchalbumart": true, "transcodingenabled": true, "auto_login": false, "getencoders":

**Comment by tilboerner** [comment]
Hi @skanduru, if I understand you correctly, and I'm not sure if I do, what you're seeing is entirely normal and expected:

* Long messages are truncated by Wireshark itself and marked as such. They go over the wire(less) completely, or CherryMusic couldn't function. 

* Sequence: This is simply how the internet works. TCP packets may arrive out of order; HTTP requests can happen in parallel with responses racing each other. 

Wireshark is a nice tool to see this kind of stuff happening. To get more fun and use out of it, you could read up on the protocols I mentioned and find out how they work.
