### ISSUE TITLE
Cherrymusic not working anymore after going from 0.37.2 to 0.38

### ISSUE THREAD

**Issue by count00zero** [devsnd/cherrymusic#641]
Hi there,

the following issue persists on my system (raspberry pi 2, debian jessie) after upgrading the great cherrymusic to version 0.38.

Whenever I want to start cherrymusic (with whichever parameter, even with --version) I get the following error and I cannot find out the reason for it.

After I switched back to 0.37.2 th error is gone; a new git clone (with 0.38) to a seperate path also leads to the error.

The error is:

Traceback (most recent call last):
  File "./cherrymusic", line 33, in <module>
    import cherrymusicserver
  File "/****/cherrymusic/cherrymusicserver/__init__.py", line 203, in <module>
    from cherrymusicserver import sqlitecache
  File "/****/cherrymusic/cherrymusicserver/sqlitecache.py", line 35, in <module>
    from test.test_descrtut import defaultdict
ImportError: No module named 'test.test_descrtut'

Best regards,
count

**Comment by drmargarido** [comment]
The defaultdict is not used in the file, so I just removed the import and everything worked

**Comment by devsnd** [comment]
@drmargarido just fixed the issue and I merged the pull request. please use the devel branch until I made the next release. Sorry for the inconvienience!

**Comment by count00zero** [comment]
Thanks a lot guys, looking great again :-)
