### ISSUE TITLE
cherrymusic-0.38.0.tar.gz was not found on this server.

### ISSUE THREAD

**Issue by tacul** [devsnd/cherrymusic#645]
![image](https://cloud.githubusercontent.com/assets/6086049/19668096/a984bdc0-9a2b-11e6-9c3b-c050366aea58.png)

**Comment by tilboerner** [comment]
Until it's fixed on the website, here's the URL: https://github.com/devsnd/cherrymusic/archive/0.38.0.tar.gz

**Comment by tacul** [comment]
thats great, thanks!

**Comment by MartijnRas** [comment]
The download worked fine just a moment ago, this can be closed.
