### ISSUE TITLE
How safe is the cherrymusic server?

### ISSUE THREAD

**Issue by ohnonot** [devsnd/cherrymusic#647]
Sorry I have to ask that here.
my cherrymusic is open to the world together with an apache instance on the same machine.
Now i know how to harden the apache server, but i'm not sure about cherrymusic.
i know nothing about python & cherrypy, or the cherrymusic server itself.
i tried to find something on cherrypy.org and their google pages, but it doesn't seem to be a hot topic (i think i found one post addressing it, more than a year ago, which basically said "not the best but suffcient").
answers, opinions?

**Comment by devsnd** [comment]
Hey @ohnonot,

CM had 2 CVEs that have been fixed quickly about a year ago. I am not aware of other security holes (after the CVEs I tried hacking CM myself but all attacks I tried failed), but this is far from any guarantee as you can imagine. This is however true of most software, unless someone does a proper audit.

Generally the security of cherrymusic is okay, passwords are hashed using sha512 with a salt generated from a UUID, which is secure [AFAIK](http://stackoverflow.com/a/786541/1191373). I know of ways to DoS the server, but I guess that's true for most applications. There seem to be 2 CVEs for CherryPy, both at least 8 years ago. There currently is no rate throttling, which might be the biggest flaw.

I cannot give you any hard facts however. All I can say is that I myself run a publicly accessable CM server, although its not running on port 80, whatever that's worth.

**Comment by ohnonot** [comment]
thanks.
it's good to hear that people are taking these things into consideration, and that the main dev is running CM publicly accessible.

i think that's good enough for me.

although it would be even better to get some definite links (hard facts) - and maybe a clearer distinction between cherrypy and cherrymusic, regarding these issues.
