### ISSUE TITLE
Personal UI improvements ideas.

### ISSUE THREAD

**Issue by Zelaf** [devsnd/cherrymusic#656]
I know this has been discussed before, but the UI (In my opinion, sorry for having such a harsh opinion) doesn't looḱ the best and a bit outdated, luckily not Ampache's default skin outdated.

I decided to write down some UI improvements that I think would work great with CherryMusic. I hope I don't offend anyone working on this. If I do, I'm writing this at 2 AM and have been trying to get streaming to different devices working for 3 days now and I've finally settled on CherryMusic. So thanks for creating it and I hope development will go well in the future.

I think, when you log in you should be introduced to your albums, or have a setting to make the player more Album oriented, as in show your albums and collection and stuff or playlist oriented where you get greeted with your playlists and things. 

"Add all tracks to current playlist" should be changed to "Add to Queue"

The current Queue/playlist window shouldn't be split in the middle but should be way smaller to the right.

In the collections window you should have a play button that plays the album directly and a plus button that adds the songs to the current Queue.

Thanks for taking your time to read this!

**Comment by devsnd** [comment]
Hey Zelaf,

Sorry for the late reply. CherryMusic is file and folder based, so we don't force any other structure on the user and I don't see that changing anytime soon.

Anyway, to your other suggestions:

  1. Making the playlist smaller in width and the file browser larger: I'm sure changing this will bring someone else to tears.
  2. The button "add all to current playlist" had received its label, when someone complained that the label "add all to queue" does not really fit, if you add the track to saved playlist... so essentially the button should change depending on the current playlist being the *queue* or another *saved playlist*. But actually, I am removing this distinction between the *queue* and the *playlists* alltogether in the UI rewrite. So I'm sorry, but I guess the label will stay as it is.
  3. Your third idea is actually a really old feature request (https://github.com/devsnd/cherrymusic/issues/415) which might or might not be done in the future.

All in all: Sorry, but the current state of cherrymusic doesn't make it easy to introduce many changes and a lot of them have already been discussed in the recent years of its existance. The reason why CM is popular nonetheless is that it's really easy to setup and its basic UI doesn't confuse to many people.

Anyway, thanks for the suggestions,
have a piece of cake and a cactus! 🍰 & 🌵

**Comment by Zelaf** [comment]
My cactus died not too long ago :,( (I'm really bad with plants).

Thanks for responding and clarifying. In the future I might be able to help with documentation. :)
