### ISSUE TITLE
[REQUEST] Paid Android app to support development

### ISSUE THREAD

**Issue by gabriellluz** [devsnd/cherrymusic#658]
Hi, I've been using CherryMusic and is just great but I couldn't find an Android app for it. Maybe my search was just not successful. I think it would be great if you create a paid Android app for CherryMusic. I think many people would pay for that, including me. That would be great and also would allow the app to have its development for a longer period. We never know when the developer wants to quit. Paying for an app like this would be very rewarding.

**Comment by tilboerner** [comment]
Hi @gabriellluz, you're right, there is no Android app for CherryMusic. I think we agree it would be nice to have one, but creating it would take considerable effort for which we simply have no time. 

A paid app is an interesting idea, although I'm not sure if it would raise enough money to pay for a sustained, full-time push to design and develop the app and make the necessary adjustments to the backend. 

To raise even 1000 EUR or USD, which would pay for two weeks' time of a developer willing to accept seriously sub-standard pay, *if* you neglect overhead like taxes and Google's cut, you would need to get 1000 people to pay 1 EUR, or 200 to pay 5. These people would rightly expect the app to work, so you'll have to front the costs of development, which would be considerably more than two weeks. Given that there would be open-source alternatives for other systems, and that we would very much like to open source the app as well, I'm afraid that developing a paid app is not a viable plan for us at this point. We haven't even talked about it, so this is only my personal opinion; but I'm pretty sure @devsnd agrees.

So although we're very flattered by your request and thank you for the suggestion, developing an Android app will remain in the hands of the intrrested community. (There's a closed issue where this was discussed; I'm currently on mobile and can't find it.)
