### ISSUE TITLE
[FR] Choose the transcoding bitrate.

### ISSUE THREAD

**Issue by jcjordyn130** [devsnd/cherrymusic#666]
Please make a option to choose the bitrate to transcode at, instead of using 160kbps.

**Comment by devsnd** [comment]
Hey Jordyn,

This is already the case. Please open the "options" modal dialog, that is
hidden behind the wrench icon in the top-navigation bar. You can choose
different encoding rates there.


2017-03-15 14:59 GMT+01:00 jcjordyn130 <notifications@github.com>:

**Comment by jcjordyn130** [comment]
Oh yeah, I thought that was to limit the streaming bitrate.
