### ISSUE TITLE
Add ID3 tag support

### ISSUE THREAD

**Issue by shoubamzlibap** [devsnd/cherrymusic#685]
This is supposed to be a feature request :)
It seems that id3 tags are currently not supported - at least not in the UI. It would be nice if id3 tags could be

- searched for (seems that search is only for file names)
- displayed  (ideally with a configurable list of tags)

Is this something which is on the road map? Or would it be hard to implement?

**Comment by devsnd** [comment]
hey @shoubamzlibap, sorry for the long wait.

Thank you for your interest in CM!

displaying id3 tags is already supported. Files shown in the file browser and in the playlist are displayed as pretty as possible with the available data.

Searching for id3 tags is a long pending issue, waiting to be tackled somewhen, see #5 (its been a long long time...)

So i`ll close this issue... you can upvote #5, maybe it will help getting it implemented

Have a nice day!
