### ISSUE TITLE
Is it possible to install Cherrymusic on a non-LAN machine?

### ISSUE THREAD

**Issue by kabads** [devsnd/cherrymusic#689]
OK - update - this is fixed - please close. It was a firewall issue. I'm installing on a headless server which isn't on my LAN. I've used a text browser (w3m) to connect to the server, so everything seems to work, and I've managed to add a user. However, when I try and connect via the public IP address, I'm not getting a response. This is running cherrymusic as root. Is there something I'm missing here?

**Comment by tilboerner** [comment]
Closed as requested in the edit.
