### ISSUE TITLE
Delete tracks

### ISSUE THREAD

**Issue by alfwro13** [devsnd/cherrymusic#692]
I would be great if it was possible to remove and delete files/songs directly from the cherrymusic UI.
Thanks

**Comment by devsnd** [comment]
Hey @alfwro13,

Thanks for your suggestion! Actually it's a feature that CM will not touch your music collection any way. That includes moving and removing files, so I'm sorry, but I will close this issue as a won't fix.

If you need to move files around, you should look into other projects that allow file management such as owncloud etc.
