### ISSUE TITLE
Tracks are not added to the queue under iOS Safari

### ISSUE THREAD

**Issue by solaris9000** [devsnd/cherrymusic#699]
Hi 

I've noticed that since upgrading from 0.39.1 to 0.41.1 the adding of tracks to the queue does not work properly under iOS 10.3.3 Safari. I can browse for files and tap on the file but the added files are not displayed and the queue remains empty. Is this a bug?

Thanks.

**Comment by tilboerner** [comment]
@solaris9000 It's a bug. I just released 0.41.2, which reverts the master branch to a working jPlayer version, and should fix this issue. Could you check if it's gone? You might have to clear the browser cache to get the new JS.

Thanks for your patience!

**Comment by tilboerner** [comment]
I'm assuming this is fixed. Feel free to reopen if the issue persists.
