### ISSUE TITLE
Does not start with cherrypy 12

### ISSUE THREAD

**Issue by impala2** [devsnd/cherrymusic#704]
A [removed configuration option](https://github.com/saltstack/salt/issues/44601) is currently used.

    AttributeError: 'Bus' object has no attribute 'timeout_monitor'

**Comment by FriedrichFroebel** [comment]
I am getting a similar error:

```
Traceback (most recent call last):
  File "cherrymusic", line 198, in <module>
    browsersetup.configureAndStartCherryPy(port) # blocks until config saved
  File "C:\Me\Music\cherrymusic\cherrymusicserver\browser
setup.py", line 166, in configureAndStartCherryPy
    cherrypy.engine.timeout_monitor.frequency = 1
AttributeError: 'Win32Bus' object has no attribute 'timeout_monitor'
```

**Comment by zhulik** [comment]
Would anybody fix it?

**Comment by devsnd** [comment]
I'll be stuck at the airport for a while today, if there's good Wifi on the
airport I'll fix it today

2017-12-29 1:35 GMT+01:00 Gleb Sinyavsky <notifications@github.com>:
