### ISSUE TITLE
http 400 failed to load file browser

### ISSUE THREAD

**Issue by voss** [devsnd/cherrymusic#722]
Hi there,

Just installed Cherrymusic and uploaded a bunch of music to the server. Before I uploaded I had a few folders with music, and that worked fine. Now with more music uploaded (~60gb) I get the "Failed to load file browser" message when I hit the "browse files" button.

I'm able to find my music if I just search for it, and it plays fine as well.

I've looked through some of the previous issues reported on this, and they didn't resolve it for me. However, I'm wondering if this could be because I have non-ascii characters in a lot of folders and filenames?

Does Cherrymusic handle non-ascii chars, or would that be an issue?

The error on the log is:

`[21/Jan/2019:16:54:38] "POST /api/listdir HTTP/1.1" 400 702 "http://mydomain:8080/" "Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0`

Thanks!

**Comment by voss** [comment]
Just updating this as it might help others too.

It does indeed look like it's due to an issue with non-ascii char's. After converting all folder names to being utf-8 friendly, I can again load the file browser.

**Comment by devsnd** [comment]
@voss Thanks Jonas.

Usually those issues come from invalid encodings (e.g. not using utf-8 everywhere) on the filesystem level. It's true that CM cannot handle those properly, but it's also in your best interest to fix those, as other software will have issues with those as well.
