### ISSUE TITLE
generate stream url?

### ISSUE THREAD

**Issue by aristosv** [devsnd/cherrymusic#723]
Is it possible for cherrymusic to generate a stream url, (like .m3u or .pls) so it can be shared with multiple streaming clients?

I have a few raspberry pi's playing music in stores, and the music stream must start playing automatically after restarting the Pi.

Can I do this using cherrymusic?

**Comment by devsnd** [comment]
No, sorry, thats currently not possible. I'll add it to the wishlist for
cherrymusic 2 though.
