### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by worldworm** [devsnd/cherrymusic#728]
your page is not available.

If the URL has changed, please open a pull request at 
https://github.com/Kickball/awesome-selfhosted or create an issue. Thank you!

https://github.com/Kickball/awesome-selfhosted/issues/1767

**Comment by devsnd** [comment]
thanks for letting me know! I'm currently on vacation but will fix it ASAP
when i find a computer somewhere!

**Comment by worldworm** [comment]
Unfortunately this project was removed from awesome-selfhosted due to inactivity. You can add this project at any time should it become active again.
Thanks for your understanding!

https://github.com/awesome-selfhosted/awesome-selfhosted
https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1767
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/1838
