### ISSUE TITLE
feature request: remote control

### ISSUE THREAD

**Issue by ScottishCherry** [devsnd/cherrymusic#730]
Hello, I have been using Mopidy, which I have not found to be satisfactory - areal pain to set up and glitch to run. But it works for my use case which is to having my music server run on a Raspberry Pi connected to my stereo. I then control Mopidy from my laptop or phone.

I absolutely love the easy setup and responsiveness of Cherry Music. However, I would like to run in on my Pi and control it remotely. But when I login over the network with my laptop or phone Cherry Music plays the audio on the remote device, not on the Pi.

Is there a way to remotely control Cherry Music? Or is this on the to do list?
Thanks in advance...

**Comment by yakking** [comment]
This is a bit of a workaround but you can connect to the PI using something like VNC connect(which comes free with the pi) and then open a browser windows on the PI and play it there, you will lose some of the responsiveness but as far as I know this isn't a feature or a planned feature of this project so it might be your best shot.

**Comment by devsnd** [comment]
Thanks for the request @ScottishCherry, it's something that i also had considered jn tje past. But I have to be honest with you: It's not going to happen for this version of cherrymusic. I have already started multiple attempts of a rewrite, but i never find enough time to get the MVP done. Anyway, until i find the time to do make cherrymusic 2, we're not going to see that feature, sorry!
